### ISSUE TITLE
[UX] Discussion on improving the instructions on how to use the Vault

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/BTCPayServer.Vault#10]
Once the vault starts it's quite unclear to people what they have to do next.
To every person I asked to try the vault, they installed it and the next question every single time was "Ok, what now?".

The current page gives this 
![Screenshot 2019-11-30 at 10 44 17](https://user-images.githubusercontent.com/36959754/69898805-6294e480-135e-11ea-9f5c-01a0b085a8a2.png)

I don't have specific idea on how we can improve this, so opening the issue for discussion.

**Comment by NicolasDorier** [comment]
the user should know why he is using the vault already. Else why would he even install it?

**Comment by Eskyee** [comment]
I agree the advance user would understands why he would be using vault software, a simple Pav 
I’m not a developer video guide and BK docs will solve that later!! For newbies  🎉

**Comment by Kukks** [comment]
I think this should come more from the integration side. Vault is merely a bridge to hardware wallets. If you present it as a way to "Sign transaction with a Hardware Wallet" or "Import from a hardware wallet", and then display either "Install Vault" or "Use Vault" dialog

**Comment by pavlenex** [comment]
`Web applications` is a very board term. I know that's technically correct term, but most people will use Vault with BTCPay. Web application term itself gives no indicator to people what has to be done. I don't think every UX issue can be solved by docs, as people generally don't read docs. 

Simple message saying something like: 
```
"The vault is now ready to be used by your BTCPay Server or other web application". 
"You can use the Vault to connect your wallet and BTCPay Server Store (Store Settings > Derivation scheme) or to spend from the wallet (Wallet > Send) (Learn More)"
```
Happy to hear other suggestions about the copy here, but I think hand-holding right this will be needed at first, as users are not familiar with how vault works. When we have docs we can link to it for sure, but vault itself is quite easy to understand.

I think what @Kukks presents is also an excellent solution, a pop up dialog once the vault is connected with exact links but this again assumes people will have their btcpay opened. Maybe a combination of both can be good.

**Comment by pavlenex** [comment]
There haven't been any complaints so far regarding this, so closing for now.
