### ISSUE TITLE
Please rename "Avalonia" titles to "BTCPay Server Vault" in Mac OS menu

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/BTCPayServer.Vault#14]
Please rename the "Avalonia" labels to "BTCPay Server Vault" in the Mac OS menu...

About Avalonia => About BTCPay Server Vault
Quit Avalonia Application => Quit BTCPay Server Vault

<img width="640" alt="Screenshot 2019-12-19 at 20 15 28" src="https://user-images.githubusercontent.com/71019/71202419-7025f600-229c-11ea-9cd9-2ddacc6a4c38.png">

**Comment by NicolasDorier** [comment]
Good catch
