### ISSUE TITLE
"The user refused to sign the transaction" (latest Trezor Firmware broken process?)

### ISSUE THREAD

**Issue by maltokyo** [btcpayserver/BTCPayServer.Vault#22]
Usually, when I sign a tx to send, I would be asked for Passphrase just once.  

Now, with the [latest trezor update](https://blog.trezor.io/firmware-updates-for-trezor-model-t-version-2-3-3-and-trezor-model-one-version-1-9-3-c94f7a3b6fea) things are broken.   Not sure if its firmware or not though.. 

I was asked for a passphrase as normal, and I entered it.  Then trezor told me to verify my password, THREE TIMES, asking me to click "confirm" each time.  I think Vault isn't used to this new process step that was introduced with the new firmware.

On the browser it displays as the below error (I closed window after that):

```
Sign the transaction with BTCPayServer Vault
 BTCPayServer successfully connected to the vault.
 Device found: Trezor_1
 The user refused to sign the transaction
```
Screenshot of the same:
![image](https://user-images.githubusercontent.com/1388507/92286191-982ab780-ef06-11ea-9177-9d32f803229d.png)

And after asking for Passphrase three times, trezor was locked on this screen for more than 5min, without signing anything:

![image](https://user-images.githubusercontent.com/1388507/92286512-97465580-ef07-11ea-86a7-25ab60b2e419.png)

**Comment by Kukks** [comment]
In advanced settings, there is a new option that fixes the breaking change
from Trezor (which breaks conpatibity with PSBT spec which is why it is off
by default).

  "always include utxo transaction if possible" or something like that

**Comment by maltokyo** [comment]
Hi @Kukks - thanks!  Ok, in this case, I think it could be good to include a very high profile message when the user selects "sign with HW wallet", warning of this "Trezor" issue.  I don't consider myself a tech-illiterate person, and I was completely lost how to sign with Trezor.  Had to sign with Electrum, and it worked fine.

**Comment by Kukks** [comment]
Yeah, we have no clue of which device you are going to sign with, so we
can't pre-check that option..(and that option is unsuitable to be on by
default as it breaks the BIP PSBT spec). Older Trezor firmware works

**Comment by maltokyo** [comment]
Yes, makes sense.  

It worked for me now, but only after you told me.

Was only thinking that there could be a small red text on the "Send" page, that says "if you use Trezor with BTCPay Vault, you must use advanced option x...." - I guess Trezor is popular enough to warrant this?
