### ISSUE TITLE
Unable to sign BTC transaction on Ledger X

### ISSUE THREAD

**Issue by balboah** [btcpayserver/BTCPayServer.Vault#25]
btcpay says "No device connected." right after "enumerating" shows in the vault.

Perhaps not compatible with the latest Ledger update?

**Comment by NicolasDorier** [comment]
What firmware do you run?

**Comment by balboah** [comment]
Tried again now with latest update to firmware: 1.2.4-5
which also reinstalled the bitcoin app which is version 1.5.1.

The Firefox version is: 83.0
Vault version: 1.0.5

same result

**Comment by NicolasDorier** [comment]
ok let me try

**Comment by NicolasDorier** [comment]
Tried on 1.3.21 Nano S. Worked. Trying to update to latest firmware and all.

**Comment by NicolasDorier** [comment]
Tried on 1.5.1 Nano S. Does not work. Will report to ledger and make announcement.

**Comment by NicolasDorier** [comment]
https://github.com/bitcoin-core/HWI/pull/403 should fix it. I will try to update.

**Comment by NicolasDorier** [comment]
Can you try to use the latest release https://github.com/btcpayserver/BTCPayServer.Vault/releases/tag/Vault%2Fv1.0.6 ? this should fix this issue. If it does, please close this issue.

**Comment by balboah** [comment]
It succeeds with the enumeration now and priceeds with signing tx.
However, Ledger shows "unverified inputs, update ledger live or 3rd party application" which I haven't seen in other applications (I've never used vault before).

It's possible to ignore this warning and continue, then it works

**Comment by NicolasDorier** [comment]
If you check this, you will not have warnings.

We were checking it by default before, but some user then got timeout problems with their ledgers... Let me know.

![image](https://user-images.githubusercontent.com/3020646/100350106-be0ab880-302c-11eb-8345-e843492b678c.png)

**Comment by balboah** [comment]
Thanks for the help
