### ISSUE TITLE
Unable to sign transaction on Trezor T

### ISSUE THREAD

**Issue by nichlor** [btcpayserver/BTCPayServer.Vault#26]
Using the p2sh segwit  derivation scheme, I connected the xpubkey of BTC wallet #2 to BTC pay server. After updating the firmware, the Trezor T no longer recognizes the wallet #2. 

I can see the funds in BTC pay server but I can not sign transaction due to Trezor T not recognizing the Derivation scheme. I created a second wallet 2 and the derivation scheme was not the same as one original derivation scheme I made.

I now have a few thousand worth of BTC i cannot access.  ( I  can now access the bitcoin through trezor software) 
additional details: i tried mac version and the windows version. of pay vault with same result. 

new trezor desktop suite 
https://suite.trezor.io/
This allowed me to make a wallet with the proper derivation scheme. I was using a p2sh segwit derivation scheme. When recreating a wallet using this scheme, it created wallet #2 with $0 and wallet #3 which was the p2sh segwit wallet with our coin.

previously it only created wallet 2. and derivation scheme was based on that wallet 2. 
i have not tried signing an outgoing transaction yet but will update if i do . 

	Update 

btcpay has pub with  -[p2sh]  tag, however wallet # 3 in trezor model T is now ypub

I have not tried to sign a transaction yet. Will update when i do.

Update, tries to sign transaction with hardware wallet.  it did not work.

What ive noticed:

The new trezor  desktop interface specifically separates sewing and p2sh and legacy wallets into separate sections.

if u use the web version, p2sh, and bip32 are grouped together. 

I think a new firmware update slightly altered the deriviation scheme, or added a password to the non main wallets i they were not already there.

i have never set a password, yet it al always  asks and i just hit the enter key on wallet and it opens my wallets. in the past i dot recall it doing that.

**Comment by nichlor** [comment]
additional details: i tried mac version and the windows version. of pay vault with same result.

**Comment by nichlor** [comment]
new trezor desktop suite 
https://suite.trezor.io/
This allowed me to make a wallet with the proper derivation scheme. I was using a p2sh segwit derivation scheme. When recreating a wallet using this scheme, it created wallet #2 with $0 and wallet #3 which was the p2sh segwit wallet with our coin.

previously it only created wallet 2. and derivation scheme was based on that wallet 2. 
i have not tried signing an outgoing transaction yet but will update if i do .

**Comment by nichlor** [comment]
btcpayserver hasxpub with  -[p2sh]  tag, however wallet # 3 in trezor model T is now ypub

I have not tried to sign a transaction yet. Will update when i do.

**Comment by NicolasDorier** [comment]
hi thanks for reporting this, no worry we'll find a way.
Did you tried to sign with BTCPayServer Vault? From what you are saying, you tried to use their desktop suite, not BTCPay Server Vault.

**Comment by nichlor** [comment]
i did try to sign  with the vault. I think the issue is somehow related to the fact that the new firmware recognizes the p2sh wallet as a different wallet then it originally was before the firmware wallet. Originally it was 2, and now its considered 3 on the new trezor software. 

wallet 2 is split into 2 wallets. so if its requesting to sign for wallet 2  it wont sign because since update  the wallet #2 p2sh is really wallet 3 now. (or a nested wallet 2 not really sure) 

this is my best guess to the cause of the issue. i have not tried to test again until i get other trezor wallet.

**Comment by NicolasDorier** [comment]
What is the error with BTCPay Vault?

I guess your issue with signing with vault is just because you manually entered the xpub rather than importing the hardware through the vault. Try to do this:

1. Create a new dummy store
2. Follow those steps to add your trezor https://www.youtube.com/watch?v=hh_cm8MKl2g (make sure to select p2sh)
3. Check that the dummy store's wallet has the same balance as your current store.
4. Send via the BTCPay Vault from the dummy store.

If you want to fix the current store, you can copy and paste the info there is in the dummy store wallet settings, into your current store wallet settings.

**Comment by NicolasDorier** [comment]
Ah also, check this box when you sign with trezor.

![image](https://user-images.githubusercontent.com/3020646/100407959-239e8980-30ad-11eb-9d6b-4690a574d446.png)

**Comment by NicolasDorier** [comment]
@nichlor did it solved your issue?

**Comment by pavlenex** [comment]
ping @nichlor please if you resolved your issue let us know so we can close it.

**Comment by nichlor** [comment]
Have not tried to move funds yet using the btc pay interface. Sorry for not closing this out. I'll see if I can try to move funds that way next time.

**Comment by yeru83** [comment]
> Have not tried to move funds yet using the btc pay interface. Sorry for not closing this out. I'll see if I can try to move funds that way next time.

Wait for it... wait for it... we're on the edge of our seats here.

**Comment by nichlor** [comment]
haha yeah. 

I never got around to this. 

> 
> 
> > Have not tried to move funds yet using the btc pay interface. Sorry for not closing this out. I'll see if I can try to move funds that way next time.
> 
> Wait for it... wait for it... we're on the edge of our seats here.

yeaaahhh, sorry.

I never got around to this, and wont anytime soon. 
Sorry for keeping this cliffhanger open for so long
