### ISSUE TITLE
L-BTC Ledger nano s & Jade HWI cold wallet. Asking for BTCPayServer.Vault wallet feature request.

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/BTCPayServer.Vault#32]
https://github.com/btcpayserver/BTCPayServer.Vault/blob/master/BTCPayServer.Hwi/HardwareWalletModels.cs

btcpay feature request. improving our hardware wallets integrations for liquid. maybe a hotwallet spend function for liquid. 
I still have a Ledger nano s for liquid testing.
but still waiting for the next batch of Jade wallet release in June.

improving  l-btc bitcoin liquid on BTCPay, makes it more assessable for merchants & better for developers storing their funds  @NicolasDorier @Kukks 
happy to help in any way with testing liquid on BTCPayServer.Vault 
cheers  ;)

**Comment by Kukks** [comment]
* Hot wallets have nothing to do with this repository.
* Jade is not yet supported on hwi
* HWI is Bitcoin only
*  NBitcoin does not support building Elements transactions using TransactionBuilder which NBXplorer uses to construct the transactions for BTCPay. 
* NBitcoin does not support PSETs that are needed in BTCPay's wallet services

**Comment by Eskyee** [comment]
Thanks this sounds like alot of work to be done still.. so I understand now why it's complicated.. because of the high fees I use liquid much more daily now. and lightning ⚡️ 
Hopefully better integration will come 🙏
