### ISSUE TITLE
Hardware Wallet connect issue

### ISSUE THREAD

**Issue by ropson56** [btcpayserver/BTCPayServer.Vault#33]
Pls i connected hardware wallet (ledger nano) At the final point of connecting. It shows error message "An unexpected error happened (Exception: Invalid status 6e00)
![image](https://user-images.githubusercontent.com/77845076/119900410-565cf980-bef9-11eb-8efd-40540930f648.png)

Please any idea of what to do. Thank you

**Comment by NicolasDorier** [comment]
@ropson56 can you try with this pre-release version https://github.com/btcpayserver/BTCPayServer.Vault/releases/tag/Vault%2Fv2.0.1 ?

**Comment by NicolasDorier** [comment]
I searched a bit about this error. Lot's of people complaining about it.

https://github.com/romanz/trezor-agent/issues/245
https://github.com/romanz/trezor-agent/issues/59
https://github.com/romanz/trezor-agent/issues/119

I don't know if that is related to us. But try the pre-release I sent you above.

**Comment by ropson56** [comment]
Hi Nicholas.
Thank you so much
 Issue has been resolved

I had to reach out to someone on Fiverr.

It was a ledger wallet issue

**Comment by NicolasDorier** [comment]
@ropson56 can you tell here what you did to solve the issue?

**Comment by ropson56** [comment]
oK.

it was a ledger wallet issue.
not btcpay.
He did it from his end. so i couldn't get to see what he did.
