### ISSUE TITLE
Ledger Nano X not recognized by Vault App

### ISSUE THREAD

**Issue by Alexbossnice** [btcpayserver/BTCPayServer.Vault#35]
Hi, i can't add my wallet because Ledger Nano X is not recognized by the vault app. 

i have on screen  : 

BTCPayServer successfully connected to the vault.
Device found: Unknown
An unexpected error happened. (Unknown device type specified) 

**Your  BTCPay Environment (please complete the following information):**

- BTCPay Server Version: v1.1.2.0   
- BTCPay Server Vault app version: 1.0.7   
- Deployment Method: raspberry pi 3b+       

**Your local environment (please complete the following information):**

- Your operating system  : Windows 10
- Browser: same on firefox and chrome                 

**Your hardware wallet details  (please complete the following information):**

- Hardware wallet name: Ledger 
- Hardware wallet version: nano X
- Hardware wallet firmware, bootloader, microcontroller verisons (where applicable): 1.3.0

**Additional context**

**Screenshots / Video / GIf (if applicable)**

**Comment by NicolasDorier** [comment]
Can you give a try to this Alpha version and let me know? https://github.com/btcpayserver/BTCPayServer.Vault/releases/tag/Vault%2Fv2.0.1

**Comment by Alexbossnice** [comment]
> 
> 
> Can you give a try to this Alpha version and let me know? https://github.com/btcpayserver/BTCPayServer.Vault/releases/tag/Vault%2Fv2.0.1

v2.0.1 tell me : No device connected (but well connected of course).

**Comment by NicolasDorier** [comment]
@Alexbossnice that's very weird. Did you update the Nano X to latest version?

**Comment by Alexbossnice** [comment]
> 
> 
> @Alexbossnice that's very weird. Did you update the Nano X to latest version?
> Have you opened the BTC app?
> If so, is Ledger Live working?
> 
> Also don't forget to stop ledger live from running hen you use Vault.

Thanks a lot for your reply : 

1.3.0 is the lastest version. BTC app open, ledger live working, now it work, i can sync my wallet.

Just name od device found is UNKNOW and name of account list is just numbers and not the names of accounts.

thanks a lot

**Comment by NicolasDorier** [comment]
This is indeed strange. Hardware wallet regularly breaks things so I keep vault up to date with the latest as much as I can. :(

Everything working fine now? Can you close the issue if that's the case?
