### ISSUE TITLE
How to use Vault application on Raspberry Pi ARM chip

### ISSUE THREAD

**Issue by PatMulligan** [btcpayserver/BTCPayServer.Vault#36]
Is there a documented method or resource on how to implement BTC Pay Server Vault on a Raspberry Pi. I would like to connect my BTCPay Server to my Ledger Nano S and the BTCPay Server Vault on the repo seems to only be for x86 chips. I'm not too technically savvy yet. 

I've seen mention of something along the lines of re-building the repo files for ARM architecture.... Is that an easy thing to do?

Can anyone help a newb out?

**Comment by NicolasDorier** [comment]
I don't think you need it?

If BTCPayServer is on a raspberry pi it does not matter. The vault is running on the computer browsing the page, which is likely x64.

**Comment by PatMulligan** [comment]
herp derp, yeah I assumed it was needed on the same device as the server. All good!
