### ISSUE TITLE
Improve the (home) landing page

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/BTCPayServer.Vault#4]
Right now, when someone installs the vault, it's quite unclear on what they have to do. You have only one CTA "Permissions" that does nothing and that's about it.

![vault page](https://user-images.githubusercontent.com/36959754/69323895-d12fbf00-0c47-11ea-938c-92e74385f2de.PNG)

Since it's still in alpha, that's understandable and maybe even better that it's only for those who understand what it does, but in the future we should improve the landing page and provide information on what people need to do in order to pair their btcpay server and a vault. 

Question: Is the only way to authorize the vault via derivation scheme?

**Comment by NicolasDorier** [comment]
@pavlenex I am still wondering to make that a web app or Avalonia app like Wasabi Wallet.
If it is Avalonia app, it would be just a screen "BTCPayServer Vault is now ready to be used".
I think actually the landing page of Vault right now should offer no option to the user. Just "Ready to be used".

**Comment by pavlenex** [comment]
@NicolasDorier  Yes that's nice idea, better than this, as I noticed 2 people I gave this to (familiar with btcpay) they kept clicking on permissions expecting something to happen

Maybe give a bit of information what it is and how it can be used. But I like that approach.

**Comment by NicolasDorier** [comment]
Closing this as I moved to avalonia.
