### ISSUE TITLE
Ledger Nano S  - No device connected

### ISSUE THREAD

**Issue by tmcphail67** [btcpayserver/BTCPayServer.Vault#43]
I have connected my Ledger Nano S(Latest firmware installed) to my Windows 10 PC - (Chrome or Firefox) with BTCPayServer Vault installed and running.  I have turned off Ledger Live as well.  With the Ledger on and Bitcoin active I attempt to add it to my store wallet and get the error "No device connected.  Any help would be appreciated!!

- BTCPay Server Version:    1.5.2
- BTCPay Server Vault app version:    2.0.1
- Deployment Method:        Docker on Ubuntu

- Your operating system Windows 10
- Browser:    Chrome, Firefox

- Hardware wallet name: Ledger Nano
- Hardware wallet version: S
- Hardware wallet firmware: 2.1.0
**Additional context**

![ptcpay-1](https://user-images.githubusercontent.com/61200660/169902554-18521bfd-2bee-4190-85b7-f75a72bf9bf6.PNG)
![btcpay-2](https://user-images.githubusercontent.com/61200660/169902581-aaec7ec5-7d8f-4b16-9bae-aff0d44c3037.PNG)

**Comment by tmcphail67** [comment]
I realized I left out the Ubuntu version I am running on is 22.04.

**Comment by NicolasDorier** [comment]
So there are currently problems with the new bitcoin app and signing caused by ledger breaking their app compatibility (https://github.com/btcpayserver/BTCPayServer.Vault/issues/43)

I would not expect the vault to not find your device, but even if it did, I think you would get issues down the road.

I really advise you to use coldcard instead of ledger. Ledger is nothing but trouble as they don't really care breaking compatibility with software developed outside of their company.

**Comment by tmcphail67** [comment]
Thank you for the response.  I really appreciate it.  We are planning to begin marketing these services to online and brick and mortar businesses soon.  My recommendation to our customers, whether we do an onsite install or they use our instance remotely is for them to use a hardware wallet. I can do a new install on Ubuntu 20.04 if you think that would help. If you would like access to our test instance in order to test let me know.  I am also getting an error on the Server Maintenance page 

"Maintenance feature requires access to SSH properly configured in BTCPay Server configuration."

I have double checked the config files and and am seeing errors in the log file.  Let me know if you would like me to post this to a separate issue.

![Capture 3](https://user-images.githubusercontent.com/61200660/170172944-8afd7d07-764e-46de-b981-374b9e1bc688.PNG)

![Capture 4](https://user-images.githubusercontent.com/61200660/170173702-cfecf220-f0cd-4a36-aef7-72dd7f04e47a.PNG)

Thanks for all or your help and the great product!!

**Comment by NicolasDorier** [comment]
For this, you need to enable ssh access to the host:

```bash
BTCPAY_ENABLE_SSH=true
. btcpay-setup.sh -i
```

**Comment by NicolasDorier** [comment]
@tmcphail67 can you open a separate issue in https://github.com/btcpayserver/btcpayserver for this ?

**Comment by NicolasDorier** [comment]
About the vault, I released a new version https://github.com/btcpayserver/BTCPayServer.Vault/releases/tag/Vault%2Fv2.0.2 I don't think it will work, but you can try.

If your wallet isn't detected, try to plug it in a different USB port.

**Comment by Gam3356** [comment]
Thank you gut!
