### ISSUE TITLE
Show a warrning about BTCPay Vault limited/no support on Safari 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/BTCPayServer.Vault#54]
![Screenshot 2022-10-20 at 14 01 49](https://user-images.githubusercontent.com/36959754/196945073-5d187c98-ef9b-474c-856c-e1b008d19ec3.png)

https://bugs.webkit.org/show_bug.cgi?id=171934

**Comment by NicolasDorier** [comment]
Vault can't work on Safari, as it doesn't support mixed content on localhost. I think we should show a warning message if we detect that the user run safari.

**Comment by pavlenex** [comment]
Sure.
