### ISSUE TITLE
BTCPay Server Vault v0.0.7 DMG, Quit unexpectedly 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/BTCPayServer.Vault#7]
BTCPay Server Vault v0.0.7 DMG for mac, Quit unexpectedly!!!  
crash immediately upon starting ,so it doesnt work!! , i give my permission in system pref, security & Privacy, since the build is from a unidentified developer, the Documented binaries signature verification is ok!!  "Apple Mac, BTCPay can improve this unidentified developer in the future"   my mac environments:  macOS Catalina 10.15.1 tested on macOS High Sierra 10.13.6 as well, same problem Quit unexpectedly, @nicolasdorier  not tested on any other platform!!

my error crash console gives me this, Error Code: 0x02000148. Trap Number: 133.  
sent my logs to @NicolasDorier 
<img width="545" alt="Screenshot 2019-11-26 at 03 41 22" src="https://user-images.githubusercontent.com/30862925/69600744-a956a780-1009-11ea-800f-7ead98fdbbe4.png">

**Comment by pavlenex** [comment]
Same happens with 0.0.8 now.

**Comment by Eskyee** [comment]
v0.0.8 same error!! in this new version @NicolasDorier

**Comment by NicolasDorier** [comment]
Closing, fixed in v0.0.9

**Comment by Eskyee** [comment]
confirmed fix, v0.0.9 
<img width="690" alt="Screenshot 2019-11-26 at 15 58 40" src="https://user-images.githubusercontent.com/30862925/69650107-02542900-1066-11ea-9af9-06681c1329d3.png">

<img width="668" alt="Screenshot 2019-11-26 at 15 58 37" src="https://user-images.githubusercontent.com/30862925/69650121-084a0a00-1066-11ea-8224-1a5fc862840b.png">
