### ISSUE TITLE
Rasberry Pi 5 (amd64) does not match system (arm64)

### ISSUE THREAD

**Issue by cdemkos** [btcpayserver/BTCPayServer.Vault#76]
dpkg: error processing archive BTCPayServerVault-2.0.8.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 BTCPayServerVault-2.0.8.deb
@rootzoll
```[tasklist]
### Tasks
```

**Comment by jl0v386** [comment]
hy

**Comment by cdemkos** [comment]
Hello jl0v386

**Comment by cdemkos** [comment]
@NicolasDorier thank you for the information.
