### ISSUE TITLE
Cant open Vault on mac Sierra 

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/BTCPayServer.Vault#8]
Error message says you have macOS 10.12.3. The application requires macOS 10.13 or later. 

Sorry if I missed this version requirement in the docs somewhere.

**Comment by britttttk** [comment]
can open in terminal instead with: 
`/Applications/BTCPayServer\ Vault.app/Contents/MacOS/BTCPayServer.Vault`

**Comment by NicolasDorier** [comment]
So it seems that .net core 3.0 does not support below 10.13. I don't think we will fix that.
Note that wasabi wallet will have the same problem next release.

**Comment by britttttk** [comment]
Closing the issue because .net core 3.0 does not support mac OS Sierra, and because I am still able to use Vault, and it works completely fine, by starting it using the command above.

**Comment by NicolasDorier** [comment]
@britttttk for information why not updgrading? it cost money? your mac don't support?

**Comment by britttttk** [comment]
too lazy @NicolasDorier don't use it really
