### ISSUE TITLE
Browsers (like Safari) can't connect to localhost without HTTPS

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/BTCPayServer.Vault#9]
We need to add an indicator that Vault can't be used with all browsers.
It seems that a [very few browsers ](https://caniuse.com/#feat=webusb)support it.
For Mac users it would be logical to try btcpay on Safari with vault and they'll see no warring of any sort.

**Comment by Kukks** [comment]
I thought we had web sockets with vault?

**Comment by pavlenex** [comment]
Maybe I am wrong, but if that's the true, it [should work on Safari,](https://caniuse.com/#search=web%20socket) when it fact it doesn't.

**Comment by Eskyee** [comment]
@Kukks maybe Safari disallows websocket communication when using self-signed certificates ??
trying to research more on this!!  https://stackoverflow.com/questions/4014055/how-to-debug-safari-silently-failing-to-connect-to-a-secure-websocket 
I read !! Chrome works fine with both the secure and non-secure host.?? we need your skills on this

**Comment by Eskyee** [comment]
not too sure but I think btcpay vault is using net sockets?? need to ask @NicolasDorier 

<img width="1440" alt="Screenshot 2019-11-27 at 02 12 10" src="https://user-images.githubusercontent.com/30862925/69688121-0eb7a080-10bd-11ea-80e1-0c1740329733.png">

<img width="434" alt="Screenshot 2019-11-27 at 02 19 13" src="https://user-images.githubusercontent.com/30862925/69688147-1d9e5300-10bd-11ea-821e-abb793080ccf.png">

https://developer.apple.com/videos/play/wwdc2018/715/  this was a good knowledge drop!!

**Comment by pavlenex** [comment]
We really need to put in the UI a list of supporter browsers, nearly ever single mac user will try this on Safari and get a very unclear message like this

![Screen Shot 2019-11-27 at 10 08 20 AM](https://user-images.githubusercontent.com/36959754/69745081-c8585500-1141-11ea-835f-28fce583d623.png)

I will transfer this issue to the main repo once @NicolasDorier elaborates on the actual supported browsers.

**Comment by NicolasDorier** [comment]
@pavlenex WebUsb is not use by the Vault at all.

**Comment by NicolasDorier** [comment]
The error on safari, I need to know if there is any logs in the browser. I would say it is because there is no async/await support in the browser and sadly there is no fool proof way to detect this.

**Comment by Eskyee** [comment]
![Screenshot 2019-11-28 at 16 23 30](https://user-images.githubusercontent.com/30862925/69821539-e1bdd780-11fb-11ea-9b06-83f1b31647df.png)

created a test store, to find any logs of error in safari, can only find this a the moment.. when I click import from the vault ... I get this error, 
<img width="1392" alt="Screenshot 2019-11-28 at 16 30 28" src="https://user-images.githubusercontent.com/30862925/69821856-b12a6d80-11fc-11ea-89d1-ddeaf642aa2e.png">
![Screenshot 2019-11-28 at 16 23 30](https://user-images.githubusercontent.com/30862925/69821875-be475c80-11fc-11ea-9f8e-1346bbe81210.png)

**Comment by Eskyee** [comment]
https://github.com/LedgerHQ/ledgerjs ledger specs here!! @pavlenex

**Comment by Eskyee** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API 
there are many specs, which spec are we using for vault ?? @NicolasDorier

**Comment by Eskyee** [comment]
<img width="1540" alt="Screenshot 2019-11-28 at 17 30 19" src="https://user-images.githubusercontent.com/30862925/69824939-5cd7bb80-1205-11ea-834b-b74487765e94.png">
<img width="1540" alt="Screenshot 2019-11-28 at 17 29 27" src="https://user-images.githubusercontent.com/30862925/69824954-6bbe6e00-1205-11ea-8666-8402fcf6c443.png">
<img width="1540" alt="Screenshot 2019-11-28 at 17 27 00" src="https://user-images.githubusercontent.com/30862925/69824979-8395f200-1205-11ea-8ef7-e1700b63ee2d.png">

some error logs from safari console

if it helps??

**Comment by Eskyee** [comment]
nothing in crash reports about safari!! @NicolasDorier 
just the old crashed BTCPay Vault versions..
<img width="1540" alt="Screenshot 2019-11-28 at 17 41 25" src="https://user-images.githubusercontent.com/30862925/69825229-71688380-1206-11ea-99c1-fa1f40e57db9.png">

**Comment by Eskyee** [comment]
<img width="1440" alt="Screenshot 2019-11-28 at 17 48 41" src="https://user-images.githubusercontent.com/30862925/69825493-7aa62000-1207-11ea-91dc-070d3cf15d4c.png">
 latest version  BTCPayServer.Vault in console

**Comment by Eskyee** [comment]
<img width="1440" alt="Screenshot 2019-11-28 at 17 58 17" src="https://user-images.githubusercontent.com/30862925/69825896-cefdcf80-1208-11ea-9e41-373fb9b996b5.png">

when I search any errors!! in console

**Comment by NicolasDorier** [comment]
@Eskyee interesting. The problem is that the browser can't connect to localhost because it is http connection on a https page... I don't know if there is any way around that.

**Comment by NicolasDorier** [comment]
There is a work around here https://stackoverflow.com/questions/39076180/https-page-was-not-allowed-to-run-insecure-content-from-safari-extension-uri

**Comment by NicolasDorier** [comment]
Ok found some resources, it seems that firefox and chrome explicitely allow mixed content for localhost (see https://bugzilla.mozilla.org/show_bug.cgi?id=903966)

@Eskyee can you try this: in `vaultbridge.js` replace localhost by 127.0.0.1 and let me know if it fixes the issue.

**Comment by NicolasDorier** [comment]
So according to w3c mixed content over http localhost should be authorized

- https://github.com/w3c/webappsec-mixed-content/commit/349501cdaa4b4dc1e2a8aacb216ced58fd316165
- https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy

BUT the safari team, in their infinite wisdom decided to now allow it, making them not compliant. https://bugs.webkit.org/show_bug.cgi?id=171934

This mean that Safari is the only browser which will not be able to support the vault.

**Comment by esky33kubernetes** [comment]
Hey sorry !! just back at my computer now!! will test in next hour @NicolasDorier

**Comment by Eskyee** [comment]
ok I`m back from testing, I did as you said!! excellent @NicolasDorier it works .. hooray 
<img width="1348" alt="Screenshot 2019-11-29 at 18 49 25" src="https://user-images.githubusercontent.com/30862925/69886324-4f8c0100-12d9-11ea-9ed6-6f8268700dd1.png">
<img width="1348" alt="Screenshot 2019-11-29 at 18 49 41" src="https://user-images.githubusercontent.com/30862925/69886335-5adf2c80-12d9-11ea-90ab-4bf86415d6b1.png">
<img width="734" alt="Screenshot 2019-11-29 at 18 49 18" src="https://user-images.githubusercontent.com/30862925/69886336-5b77c300-12d9-11ea-9493-47626f393e68.png">
<img width="734" alt="Screenshot 2019-11-29 at 18 49 32" src="https://user-images.githubusercontent.com/30862925/69886342-629ed100-12d9-11ea-87fc-ce03bf9025d8.png">
<img width="1348" alt="Screenshot 2019-11-29 at 18 49 53" src="https://user-images.githubusercontent.com/30862925/69886346-69c5df00-12d9-11ea-9b1c-961026857e11.png">
<img width="866" alt="Screenshot 2019-11-29 at 18 50 25" src="https://user-images.githubusercontent.com/30862925/69886350-72b6b080-12d9-11ea-8db3-daf30a568916.png">

just as you said it would, well done, ;)

**Comment by Eskyee** [comment]
shizz be working on Apple Safari ... ooooooooh bwoy !! excellent stuff

**Comment by Eskyee** [comment]
![Screenshot 2019-11-29 at 19 00 03](https://user-images.githubusercontent.com/30862925/69886594-9d553900-12da-11ea-803f-dcc9a94a4e1b.png)

**Comment by NicolasDorier** [comment]
There is still the problem even with the latest version. It worked for esky at one point because he was running in debug mode on localhost.

This is a bug from safari, they work to fix it, but there is nothing I can do: https://bugs.webkit.org/show_bug.cgi?id=171934

**Comment by tobq** [comment]
@NicolasDorier any solutions?
